add_executable(online_training_node src/online_training/online_training.cpp)
add_executable(offline_collect_node src/offline_collect/offline_collect.cpp)
add_executable(test_model_node src/online_training/test_model.cpp)
add_executable(test_rand_generator_node src/online_training/test_rand_generator.cpp)